export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_LOADING="GET_CART_LOADING"
export const GET_CART_ERROR="GET_CART_ERROR"

export const ADD_CART_SUCCESS="ADD_CART_SUCCESS"
export const ADD_CART_LOADING="ADD_CART_LOADING"
export const ADD_CART_ERROR="ADD_CART_ERROR"

export const DELETE_CART_SUCCESS="DELETE_CART_SUCCESS"
export const DELETE_CART_LOADING="DELETE_CART_LOADING"
export const DELETE_CART_ERROR="DELETE_CART_ERROR"